Raise minimum compiler to rust 1.56
Required by our dependency on clap.

    error: failed to download `clap v3.2.1`

    Caused by:
      unable to get packages from source

    Caused by:
      failed to parse manifest at `github.com-1ecc6299db9ec823/clap-3.2.1/Cargo.toml`

    Caused by:
      feature `edition2021` is required

      this Cargo does not support nightly features, but if you
      switch to nightly channel you can add
      `cargo-features = ["edition2021"]` to enable this feature