Raise minimum rustc to 1.64
Required by clap 4.1 / clap_lex 0.3.1:

    error: package `clap_lex v0.3.1` cannot be built because it requires rustc 1.64.0 or newer